### ISSUE TITLE
Pengembangan

### ISSUE THREAD

**Issue by ryn-crypto** [Densu341/restfull_api#1]
apa yang akan di kemabangkan dari rest server ini ?

**Comment by Densu341** [comment]
saya ingin mengembangkan agar rest server dapat menerima request dengan parameter search.

**Comment by ryn-crypto** [comment]
untuk mengembangkan fitur serach bisa dilakukan di front end, dengan menggunakan data yang di ambil dari rest server, kemudian diolah dengan membandingkan kemiripan antara data yang di input dari user dan juga data json

**Comment by ryn-crypto** [comment]
jika ingin menambahkan fitur search di back end, maka api bisa menerima parameter yang akan di query ke database dengan membandingkan kemiripan data yang ada
